- build.gradle.kts
- naiserator-dev.yaml
- naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/Application.kt
- src/main/kotlin/no/nav/syfo/api/controllers/BehandlendeEnhetADController.kt
- src/main/kotlin/no/nav/syfo/api/controllers/BehandlendeEnhetController.kt
- src/main/kotlin/no/nav/syfo/consumers/TilgangConsumer.kt
- src/main/kotlin/no/nav/syfo/exception/ControllerExceptionHandler.kt
- src/main/kotlin/no/nav/syfo/oidc/OIDCUtil.kt
- src/main/kotlin/no/nav/syfo/selftest/Selftest.kt
- src/main/resources/application.yaml
- src/test/kotlin/no/nav/syfo/LocalApplication.kt
- src/test/kotlin/no/nav/syfo/controller/BehandlendeEnhetADControllerTest.kt
- src/test/kotlin/no/nav/syfo/localconfig/LocalApplicationConfig.kt
- src/test/kotlin/no/nav/syfo/testhelper/OidcTestHelper.kt
- src/test/resources/application.yaml
> Bump token-support for spring

- build.gradle.kts
- naiserator-dev.yaml
- naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/config/ApplicationConfig.kt
- src/main/kotlin/no/nav/syfo/consumers/NorgConsumer.kt
- src/main/kotlin/no/nav/syfo/consumers/PersonConsumer.kt
- src/main/kotlin/no/nav/syfo/consumers/pdl/PdlConsumer.kt
- src/main/kotlin/no/nav/syfo/consumers/pdl/PdlPersonResponse.kt
- src/main/kotlin/no/nav/syfo/consumers/pdl/PdlRequest.kt
- src/main/kotlin/no/nav/syfo/consumers/sts/StsConsumer.kt
- src/main/kotlin/no/nav/syfo/domain/PersonIdentNumber.kt
- src/main/kotlin/no/nav/syfo/domain/model/ArbeidsfordelingCriteria.kt
- src/main/kotlin/no/nav/syfo/service/EnhetService.kt
- src/main/kotlin/no/nav/syfo/util/CredentialUtil.kt
- src/main/kotlin/no/nav/syfo/util/PersonIdentUtil.kt
- src/main/kotlin/no/nav/syfo/util/RequestUtil.kt
- src/main/resources/pdl/hentPerson.graphql
- src/test/kotlin/no/nav/syfo/controller/BehandlendeEnhetADControllerTest.kt
- src/test/kotlin/no/nav/syfo/testhelper/PdlPersonResponseGenerator.kt
- src/test/resources/application.yaml
If empty GT, send GT when requesting Arbeidsfordeling to Norg. Also add diskresjonskode to get correct Arbeidsfordeling for Kode6 and Kode7
> Handle empty GT

- src/main/kotlin/no/nav/syfo/consumer/norg/NorgConsumer.kt
- src/main/kotlin/no/nav/syfo/consumer/pdl/GeografiskTilknytning.kt
- src/main/kotlin/no/nav/syfo/consumer/pdl/PdlConsumer.kt
- src/main/kotlin/no/nav/syfo/consumer/pdl/PdlGeografiskTilknytningResponse.kt
- src/main/kotlin/no/nav/syfo/consumer/pdl/PdlRequestFailedException.kt
- src/test/kotlin/no/nav/syfo/behanlendeenhet/BehandlendeEnhetADControllerTest.kt
Throw exception if no valid response is returned from PDL. Throw exception is gtType is UDEFINERT. If gtType is valid(BYDEL, KOMMUNE or Bydel), but the gtValue is null, then set GT to null. When GT is null, Norg2 will return 0393 NAVUtland as Arbeidsfordeling.
> Throw exception if no GT is returned from PDL or gtType is UDEFINERT

- src/main/kotlin/no/nav/syfo/application/api/ApiFeature.kt
- src/main/kotlin/no/nav/syfo/client/pdl/GeografiskTilknytningNotFoundException.kt
- src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
- src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlGeografiskTilknytningResponse.kt
- src/test/kotlin/no/nav/syfo/behandlendeenhet/api/internad/BehandlendeEnhetApiSpek.kt
- src/test/kotlin/no/nav/syfo/behandlendeenhet/api/system/BehandlendeEnhetSystemApiSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
- src/test/kotlin/no/nav/syfo/testhelper/mock/PdlMock.kt
Return Http 204 NoContent if No Geografisk tilknytning was found in response from PDL
> Return Http 204 NoContent if No Geografisk tilknytning was found

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- build.gradle.kts
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/database/Database.kt
- src/main/kotlin/no/nav/syfo/application/database/DatabaseModule.kt
- src/main/resources/application.conf
- src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
- src/main/resources/db/migration/V1_1__grant_to_cloudsqliamuser.sql
- src/main/resources/db/migration/V1_2__create_isyfoanalyse_user.sql
- src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Det meste av config er kopiert fra `isdialogmelding`
> Add database dependencies and config setup

- src/main/kotlin/no/nav/syfo/behandlendeenhet/EnhetService.kt
- src/main/kotlin/no/nav/syfo/client/norg/NorgClient.kt
- src/main/kotlin/no/nav/syfo/client/norg/domain/ArbeidsfordelingCriteria.kt
- src/test/kotlin/no/nav/syfo/behandlendeenhet/api/internad/BehandlendeEnhetApiSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/generator/GeneratePerson.kt
- src/test/kotlin/no/nav/syfo/testhelper/mock/Norg2Mock.kt
Etter samtale med NORG har vi blitt bedt om å legge ved en behandlingstype `ae0106` som indikerer at det er NAV Utland.
> Add behandlingstype flag when person is NAV Utland

- build.gradle.kts
Fix snyk issue with proof of concept. Isn't yet fixed in all major packages, so two of the upgrades are in constraints.
> jackson_databind --> 2.13.4

- .github/workflows/kafka.yaml
- .nais/kafka/behandlendeenhet.yaml
- .nais/kafka/dev.json
- .nais/kafka/prod.json
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- build.gradle.kts
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/kafka/JacksonKafkaSerializer.kt
- src/main/kotlin/no/nav/syfo/application/kafka/Kafka.kt
- src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestKafka.kt
Inspirert av det som ligger i isdialogmote
> Add kafka config

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- build.gradle.kts
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationUtils.kt
- src/main/kotlin/no/nav/syfo/application/kafka/Kafka.kt
- src/main/kotlin/no/nav/syfo/identhendelse/kafka/IdenthendelseConsumerService.kt
- src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseConsumerConfig.kt
- src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseDTO.kt
- src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseMetric.kt
- src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseTask.kt
- src/main/kotlin/no/nav/syfo/util/UnboundedDispatcher.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestKafka.kt
> Add identhendelse-config

- src/main/kotlin/no/nav/syfo/App.kt
Ser at noen kall til syfobehandlendeenhet fra andre app'er ikke kommer fram, så forsøker å øke størrelsen på thread pool'en.
> Increase thread pool

- .github/dependabot.yaml
- build.gradle.kts
Sånn at dependabot finner avhengigheter og lagrer ukentige PRs på oppdateringer. Grupperer minor og patch-oppdatering i samme PR.
> Fix versions and dependabot

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Gir tilang til system-api slik at meroppfolging-backend kan hente behandlende enhet for sykmeldt til å sjekke pilotkontor
> IS-2366: Allow meroppfolging-backend access to system api

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
..midlertidig løsning for å kunne journalføre for pilotbrukere av mer oppfølging.
> Give access to Esyfovarsel

- src/main/kotlin/no/nav/syfo/behandlendeenhet/EnhetService.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/api/BehandlendeEnhetDTO.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/api/internad/BehandlendeEnhetAPI.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/domain/Oppfolgingsenhet.kt
- src/test/kotlin/no/nav/syfo/behandlendeenhet/api/internad/BehandlendeEnhetApiSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
- src/test/kotlin/no/nav/syfo/testhelper/generator/GeneratePerson.kt
Med disse tilpasningene vil det være mulig for frontend å sette oppfølgingsenhet - dvs ikke bare til Nav utland som i dag, men til en vilkårlig enhet.
> IS-3139: Tilpasninger i post-kall

- src/main/kotlin/no/nav/syfo/behandlendeenhet/EnhetService.kt
- src/main/kotlin/no/nav/syfo/infrastructure/database/repository/EnhetRepository.kt
- src/test/kotlin/no/nav/syfo/behandlendeenhet/api/internad/BehandlendeEnhetApiSpek.kt
Skal alltid være mulig å tildele til Nav Utland
> IS-3233: Add NAV Utland to mulige

- src/main/kotlin/no/nav/syfo/behandlendeenhet/Enhet.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/EnhetService.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/IEnhetRepository.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/api/BehandlendeEnhetResponseDTO.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/api/internad/BehandlendeEnhetAPI.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/domain/BehandlendeEnhet.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/domain/Enhet.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/domain/Oppfolgingsenhet.kt
- src/main/kotlin/no/nav/syfo/domain/BehandlendeEnhet.kt
- src/main/kotlin/no/nav/syfo/identhendelse/IdenthendelseService.kt
- src/main/kotlin/no/nav/syfo/infrastructure/client/norg/NorgClient.kt
- src/main/kotlin/no/nav/syfo/infrastructure/database/repository/EnhetRepository.kt
- src/main/kotlin/no/nav/syfo/infrastructure/database/repository/POppfolgingsenhet.kt
- src/test/kotlin/no/nav/syfo/behandlendeenhet/api/internad/BehandlendeEnhetApiSpek.kt
- src/test/kotlin/no/nav/syfo/behandlendeenhet/api/system/BehandlendeEnhetSystemApiSpek.kt
- src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
- src/test/kotlin/no/nav/syfo/infrastructure/cronjob/RemoveOppfolgingsenhetCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/infrastructure/cronjob/ReturnToSenderIfNoVeilederCronjobSpek.kt
Inkluder tidspunkt og veilederident for oppfølgingsenhet når denne har en verdi.
> IS-3171: Inkluder tidspunkt og veilederident for oppfolgingsenhet

- src/main/kotlin/no/nav/syfo/behandlendeenhet/api/BehandlendeEnhetResponseDTO.kt
- src/test/kotlin/no/nav/syfo/behandlendeenhet/api/internad/BehandlendeEnhetApiSpek.kt
Vet ikke helt hvordan en `OffsetDateTime` skal tas i mot i frontend - så endrer til `LocalDateTime` i DTO'en.
> IS-3171: Inkluder tidspunkt som LocalDateTime

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/behandlendeenhet/api/BehandlendeEnhetResponseDTO.kt
- src/test/kotlin/no/nav/syfo/behandlendeenhet/api/internad/BehandlendeEnhetApiSpek.kt
- src/test/kotlin/no/nav/syfo/behandlendeenhet/api/system/BehandlendeEnhetSystemApiSpek.kt
Omsider tror jeg vi kan forenkle her (men det er noen PR'er i andre app'er som må merges først)
> IS-3171: Fjerner ubrukte felter i BehandlendeEnhetResponseDTO

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
> IS-2826: Add tracing

- src/main/kotlin/no/nav/syfo/behandlendeenhet/EnhetService.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/IEnhetRepository.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/api/TildelHistorikkResponseDTO.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/api/TildeltHistorikkResponseDTO.kt
- src/main/kotlin/no/nav/syfo/behandlendeenhet/api/internad/BehandlendeEnhetAPI.kt
- src/main/kotlin/no/nav/syfo/infrastructure/database/repository/EnhetRepository.kt
- src/test/kotlin/no/nav/syfo/behandlendeenhet/api/internad/BehandlendeEnhetApiSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
Har laget et forslag til endepunkt og datastruktur for å levere tildelingshistorikk.
> IS-3138: Lagt til endepunkt for å hente ut tildelingshistorikk

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Rydder også i gamle dev-tilganger som ikke lenger er i bruk.
> IS-3351: Add ismeroppfolging to inbound
